mutable struct Model{T <: Real}
    y::Vector{T}
    X::Matrix{T}
    beta_hat::Vector{T}
    num_obs::Int
    dof_reg::Int
    dof_resid::Int
    dof_total::Int
    rmse::T
    llk::T
    aic::T
    bic::T
    r2::T
    r2_adj::T
    residuals::Vector{T}
    mse::T
    msr::T
    mst::T
    sse::T
    ssr::T
    sst::T
    std_error::Vector{T}
    t_value::Vector{T}
    t_test_p_value::Vector{T}
    f_value::T
    f_test_p_value::T
    se_beta::Vector{T}
end